[package]
name = "nicho/be-a-toilet"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
GoodSignal = "call23re/goodsignal@^0.2.2"
Viewport = "aspecky/viewportfitter@^1.0.0"
ZonePlus = "mattschrubb/zoneplus@^3.2.0"
BridgeNet2 = "ffrostflame/bridgenet2@^1.0.0"
Reflex = "littensy/reflex@^4.3.1"
Sift = "csqrl/sift@0.0.8"
Fusion = "elttob/fusion@^0.2.0"
Janitor = "howmanysmall/janitor@^1.15.7"

[server-dependencies]
ProfileService = "alreadypro/profileservice@^1.0.4"

[place]
shared-packages = "game.ReplicatedStorage.Packages"